###recuperar informacion del pokemon ditto
GET http://localhost:1234/pokemon/ditto
###separar las request es necesario para hacer peticiones especificas
POST http://localhost:1234/pokemon

Content-Type: application/json

{
    "name":"ditto",
    "type":"normal",
    "moves":[
        "transform"
    ]
}